services:
  flyway:
    image: flyway/flyway:10
    command: -connectRetries=60 migrate
    environment:
      FLYWAY_URL: jdbc:postgresql://${POSTGRES_HOST:-localhost}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-monitoramento_saude}
      FLYWAY_USER: ${POSTGRES_USER}
      FLYWAY_PASSWORD: ${POSTGRES_PASSWORD}
      FLYWAY_SCHEMAS: monitoramento
      FLYWAY_BASELINE_ON_MIGRATE: "true"
    volumes:
      - ./db/migration:/flyway/sql:ro

  api:
    build: .
    environment:
      ENV: ${ENV:-prod}
      GUNICORN_WORKERS: ${GUNICORN_WORKERS:-2}
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST:-localhost}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-monitoramento_saude}

      # Configurações da API
      API_KEYS: ${API_KEYS}
      API_SECRET: ${API_SECRET}
      REQUIRE_HMAC: ${REQUIRE_HMAC:-false}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-http://localhost:8000}
      ENFORCE_ORIGIN_CHECK: ${ENFORCE_ORIGIN_CHECK:-false}
    ports:
      - "8000:8000"
    depends_on:
      flyway:
        condition: service_completed_successfully
